ChatGPT_WebUI/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers
from chatgpt_api_ui.viewsets import ChatViewSet, SystemRoleViewSet, ChatMessageViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'chats', ChatViewSet)
router.register(r'system_roles', SystemRoleViewSet)
router.register(r'chat_messages', ChatMessageViewSet)


urlpatterns = [
    path('', include('chatgpt_api_ui.urls', namespace='chatgpt')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
]

chatgpt_api_ui/urls.py
from django.urls import path, re_path
from chatgpt_api_ui import views

app_name = 'chatgpt_api_ui'

urlpatterns = [
    path('', views.chat_view, name="chat_ui"),
    re_path(r'^(?P<pk>\d+)/$', views.chat_view, name="chat_pk"),
    path("new_chat/", views.create_chat, name="new_chat"),
    path("new_system_role", views.create_system_role, name="new_system_role"),
    path("api/chat_completion/", views.chat_completion_view),
]

chatgpt_api_ui/models.py
import uuid
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class SystemRole(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return f"{self.name}"


class Chat(models.Model):
    # https://platform.openai.com/docs/api-reference/chat/create
    TEMPERATURE_HELP = "What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic."
    PRESENCE_PENALTY_HELP = "Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics."
    FREQUENCY_PENALTY_HELP = "Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim."

    system_role = models.ForeignKey('SystemRole', on_delete=models.CASCADE)

    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)
    chat_id = models.AutoField(primary_key=True)
    uuid = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)

    temperature = models.DecimalField(default=1, max_digits=2, decimal_places=1, validators=[MinValueValidator(0), MaxValueValidator(2)], help_text=TEMPERATURE_HELP)
    max_tokens = models.PositiveIntegerField(default=4096)
    presence_penalty = models.DecimalField(default=0, max_digits=2, decimal_places=1, validators=[MinValueValidator(-2), MaxValueValidator(2)], help_text=PRESENCE_PENALTY_HELP)
    frequency_penalty = models.DecimalField(default=0, max_digits=2, decimal_places=1, validators=[MinValueValidator(-2), MaxValueValidator(2)], help_text=FREQUENCY_PENALTY_HELP)

    def __str__(self):
        return f"{self.name}"


class ChatMessage(models.Model):
    USER = "user"
    ASSISTANT = "assistant"
    ROLE_CHOICES = [
        (USER, 'User'),
        (ASSISTANT, 'Assistant'),
    ]

    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name="chat_messages")
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    role = models.CharField(max_length=9, choices=ROLE_CHOICES, default=USER)
    completion_tokens = models.PositiveIntegerField(default=0)
    prompt_tokens = models.PositiveIntegerField(default=0)
    total_tokens = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.role}: {self.content[:10]}"

chatgpt_api_ui/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
from chatgpt_api_ui.models import SystemRole, Chat


class SystemRoleForm(forms.ModelForm):
    class Meta:
        model = SystemRole
        fields = ['name', 'description']


class ChatForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ['system_role', 'name', 'temperature', 'max_tokens', 'presence_penalty', 'frequency_penalty']

    temperature = forms.DecimalField(help_text=Chat.TEMPERATURE_HELP, validators=[MinValueValidator(0), MaxValueValidator(2)])
    presence_penalty = forms.DecimalField(help_text=Chat.PRESENCE_PENALTY_HELP, validators=[MinValueValidator(-2), MaxValueValidator(2)])
    frequency_penalty = forms.DecimalField(help_text=Chat.FREQUENCY_PENALTY_HELP, validators=[MinValueValidator(-2), MaxValueValidator(2)])

chatgpt_api_ui/views.py
import json
import logging
from datetime import datetime

from django.urls import reverse
from django.http import JsonResponse
from django.shortcuts import render, redirect
from chatgpt_api_ui.models import Chat, ChatMessage
from django.contrib.auth.decorators import login_required
from chatgpt_api_ui.forms import SystemRoleForm, ChatForm
from chatgpt_api_ui.utilities import chat_completion

logger = logging.getLogger('chatgpt_webui')


@login_required(login_url='/admin/login/')
def chat_view(request, pk=None):
    if pk is None:
        # If no primary key is provided, get the primary key of the newest Chat object
        chat = Chat.objects.order_by('-pk').first()
        if chat is not None:
            return redirect(reverse('chatgpt_api_ui:chat_pk', args=[chat.pk]))

    # Render the chat_view.html template as before
    messages = ChatMessage.objects.all()
    chats = Chat.objects.all()
    context = {
        "chats": chats,
        "messages": messages
    }
    return render(request, 'chatgpt_api_ui/chat_view.html', context)


@login_required
def chat_completion_view(request):
    if request.method == "POST":
        # Parse the request body as JSON and retrieve the chatPK and message fields
        data = json.loads(request.body)
        chat_pk = data.get("chatPK")
        message = data.get("message")

        try:
            # Retrieve the Chat object associated with the chat PK
            # If the Chat object does not exist, create a new one with the specified PK
            chat_obj = Chat.objects.get_or_create(pk=chat_pk)[0]

            # Create messages list
            messages = list()
            messages.append({"role": "system", "content": chat_obj.system_role.description.replace("{{date}}", datetime.now().strftime("%d.%m.%Y"))})
            messages_obj = chat_obj.chat_messages.all()

            for msg in messages_obj:
                messages.append({"role": msg.role, "content": msg.content})

            logger.info('New message: {}'.format(message))
            messages.append({"role": "user", "content": message})

            # Get chat completion response
            response = chat_completion(messages, chat_obj.temperature, chat_obj.presence_penalty, chat_obj.frequency_penalty)
        except Exception as e:
            logger.error(e)
            return JsonResponse({'error': f"{e}"}, status=500)

        # Create ChatMessage object with user input
        new_message = ChatMessage.objects.create(chat_id=chat_obj.pk)
        new_message.content = message
        new_message.save()

        # Parse response
        response_message = response.choices[0].message.content
        logger.info('API response: {}'.format(response_message))

        # Create ChatMessage object for Assistant response
        new_message = ChatMessage.objects.create(chat_id=chat_obj.pk)
        new_message.content = response_message
        new_message.role = ChatMessage.ASSISTANT
        new_message.completion_tokens = response.usage.completion_tokens
        new_message.prompt_tokens = response.usage.prompt_tokens
        new_message.total_tokens = response.usage.total_tokens
        new_message.save()

        return JsonResponse({}, status=200)
    else:
        return JsonResponse({"error": "Invalid request method"}, status=500)


def create_system_role(request):
    if request.method == 'POST':
        form = SystemRoleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('chatgpt_api_ui:chat_ui'))
    else:
        initial_values = {'name': "Helpful Assistant", "description": "You are a helpful assistant."}
        form = SystemRoleForm(initial=initial_values)

    return render(request, 'chatgpt_api_ui/new_system_role.html', {'form': form})


def create_chat(request):
    if request.method == 'POST':
        form = ChatForm(request.POST)
        if form.is_valid():
            chat = form.save()
            return redirect(reverse('chatgpt_api_ui:chat_pk', args=[chat.pk]))
    else:
        chat_name = "Chat {}".format(Chat.objects.count() + 1)
        initial_values = {'name': chat_name, 'temperature': 1, 'presence_penalty': 0, 'frequency_penalty': 0}
        form = ChatForm(initial=initial_values)

    return render(request, 'chatgpt_api_ui/new_chat.html', {'form': form})

chatgpt_api_ui/templates/chatgpt_api_ui/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'chatgpt_api_ui/icons/favicon.png' %}"/>
    {% block head_links %}

    {% endblock %}
</head>
<body>
{% block content %}


{% endblock %}
</body>
</html>

chatgpt_api_ui/templates/chatgpt_api_ui/chat_view.html
{% extends 'chatgpt_api_ui/base.html' %}

{% load static %}

{% block title %}ChatGPT API{% endblock %}


{% block head_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'chatgpt_api_ui/css/chat_ui.css' %}">
{% endblock %}


{% block content %}
    <div class="container">
        <div class="sidebar">
            <div class="sidebar-content-top">
                <ul>
                    {% for chat in chats %}
                        <li><a href="{% url 'chatgpt:chat_pk' chat.pk %}">{{ chat.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="sidebar-content-bottom">
                <ul>
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a href="{% url 'chatgpt:new_system_role' %}">New System Role</a></li>
                    <li><a href="{% url 'chatgpt:new_chat' %}">New Chat</a></li>
                </ul>
            </div>
        </div>

        <div class="content" id="app"></div>

        {#    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>#}

        <!-- Load React. -->
        <!-- Note: when deploying, replace "development.js" with "production.min.js". -->
        <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
        <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
        <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>

        <!-- Load JS modules. -->
        <script type="text/babel" src="{% static 'chatgpt_api_ui/js/api-requests.js' %}"></script>
        <script type="text/babel" src="{% static 'chatgpt_api_ui/js/messages-list.js' %}"></script>
        <script type="text/babel" src="{% static 'chatgpt_api_ui/js/chat-input.js' %}"></script>
        <script type="text/babel" src="{% static 'chatgpt_api_ui/js/chat_app.js' %}"></script>
    </div>
{% endblock %}

chatgpt_api_ui/templates/chatgpt_api_ui/new_chat.html
{% extends 'chatgpt_api_ui/base.html' %}

{% load static %}

{% block title %}Create Chat{% endblock %}


{% block head_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'chatgpt_api_ui/css/form_style.css' %}">
{% endblock %}


{% block content %}
    <h1>Create Chat</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.system_role.id_for_label }}">System Role:</label>
            {{ form.system_role }}
        </div>
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">Name:</label>
            {{ form.name }}
        </div>
        <div class="form-group">
            <label for="{{ form.max_tokens.id_for_label }}">Max Tokens:</label>
            {{ form.max_tokens }}
        </div>

        <div class="form-group">
            <label for="{{ form.temperature.id_for_label }}">Temperature:</label>
            {{ form.temperature }}
            <br>
            {{ form.temperature.help_text }}
            <br><br>
        </div>

        <div class="form-group">
            <label for="{{ form.presence_penalty.id_for_label }}">Presence Penalty:</label>
            {{ form.presence_penalty }}
            <br><br>
            {{ form.presence_penalty.help_text }}
            <br>

        </div>
        <div class="form-group">
            <label for="{{ form.frequency_penalty.id_for_label }}">Frequency Penalty:</label>
            {{ form.frequency_penalty }}
            <br><br>
            {{ form.frequency_penalty.help_text }}
            <br>
        </div>
        <br>
        <input type="submit" value="Save">
        <button type="button" onclick="window.location.href='{% url 'chatgpt:chat_ui' %}'" class="cancel-button">Cancel</button>
    </form>
{% endblock %}

chatgpt_api_ui/templates/chatgpt_api_ui/new_system_role.html
{% extends 'chatgpt_api_ui/base.html' %}

{% load static %}

{% block title %}Create System Role{% endblock %}


{% block head_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'chatgpt_api_ui/css/form_style.css' %}">
{% endblock %}


{% block content %}
    <h1>Create System Role</h1>
    <form method="post">
        {% csrf_token %}
        <label for="{{ form.name.id_for_label }}">Name:</label>
        {{ form.name }}
        <label for="{{ form.description.id_for_label }}">Description:</label>
        {{ form.description }}
        <input type="submit" value="Save">
        <button type="button" onclick="window.location.href='{% url 'chatgpt:chat_ui' %}'" class="cancel-button">Cancel</button>
    </form>
{% endblock %}